### ISSUE TITLE
[Suggestion] Text rendering

### ISSUE THREAD

**Issue by wozniak** [0x3C50/Renderer#1]
It would be really cool if text rendering was possible with `Renderer2d`. Maybe it could even support TTF fonts or something.

**Comment by 0x3C50** [comment]
I do have an idea to implement this, however my current text rendering implementation I have in another project is very meh, and I need actual good examples to know how to do better. If you find any, let me know, and I'll implement them

**Comment by ada-mmmm** [comment]
> I do have an idea to implement this, however my current text rendering implementation I have in another project is very meh, and I need actual good examples to know how to do better. If you find any, let me know, and I'll implement them

hoping you can do this! would be really cool!

**Comment by ada-mmmm** [comment]
transparency would be nice :)

**Comment by 0x3C50** [comment]
Added in https://github.com/0x3C50/Renderer/commit/bb334952b436de966abf8340597fb09016b0a561
