### ISSUE TITLE
some examples?

### ISSUE THREAD

**Issue by bezumnui** [0x3C50/Renderer#16]
Yeap. There is some javadoc.
For example will take Renderer3d#renderFilled
params:
start - The start coordinate of the block
dimensions - The dimensions of the block
color - The color of the filling

so I'm trying to call render by:
 var filled =  Renderer3d.renderFilled(new Vec3d(0 - .5, 0 - .5, 0 - .5), new Vec3d(1, 1, 1), Color.CYAN);
 filled.drawWithVBO(Renderer3d.getEmptyMatrixStack());
 
 and result is:

<img width="966" alt="image" src="https://user-images.githubusercontent.com/57602929/195985466-cde565f1-8739-4d9c-a337-b8ff1e8fd05f.png">

I know that my code is bad. Because I don't know how to use this method. Help me please :)

**Comment by 0x3C50** [comment]
you're not passing in the context matrixstack correctly, the matrixstack holds all rotations and transformations, including camera rotation. where are you calling the renderer from?

**Comment by bezumnui** [comment]
ok. u are right) thank you. But example will be helpful. Something like:

## Drawing cyan block overlay:
```
@Mixin(WorldRenderer.class)
public class WorldRendererMixin {
    @Inject(method = "drawBlockOutline", at = @At(value = "HEAD", target = "Lnet/minecraft/client/render/WorldRenderer;drawCuboidShapeOutline(Lnet/minecraft/client/util/math/MatrixStack;Lnet/minecraft/client/render/VertexConsumer;Lnet/minecraft/util/shape/VoxelShape;DDDFFFF)V"))
    public void drawBlockOutlineMixin(MatrixStack matrices, VertexConsumer vertexConsumer, Entity entity, double cameraX, double cameraY, double cameraZ, BlockPos pos, BlockState state, CallbackInfo ci) {
        //    creating a render object
        var filled = Renderer3d.renderFilled(new Vec3d(pos.getX(), pos.getY(), pos.getZ()), new Vec3d(1, 1, 1), Color.CYAN);
        //    drawing object
        filled.drawWithVBO(matrices);
        //    deleting object from heap
        filled.delete();
    }
}
```

**Comment by 0x3C50** [comment]
> ok. u are right) thank you. But example will be helpful. Something like:
> ## Drawing cyan block overlay:
> 
> ```
> @Mixin(WorldRenderer.class)
> public class WorldRendererMixin {
>     @Inject(method = "drawBlockOutline", at = @At(value = "HEAD", target = "Lnet/minecraft/client/render/WorldRenderer;drawCuboidShapeOutline(Lnet/minecraft/client/util/math/MatrixStack;Lnet/minecraft/client/render/VertexConsumer;Lnet/minecraft/util/shape/VoxelShape;DDDFFFF)V"))
>     public void drawBlockOutlineMixin(MatrixStack matrices, VertexConsumer vertexConsumer, Entity entity, double cameraX, double cameraY, double cameraZ, BlockPos pos, BlockState state, CallbackInfo ci) {
>         //    creating a render object
>         var filled = Renderer3d.renderFilled(new Vec3d(pos.getX(), pos.getY(), pos.getZ()), new Vec3d(1, 1, 1), Color.CYAN);
>         //    drawing object
>         filled.drawWithVBO(matrices);
>         //    deleting object from heap
>         filled.delete();
>     }
> }
> ```

I recommend not using drawWithVBO() if you're just drawing it once, that's overkill. VBOs are designed to cache big render actions so they don't have to be regenerated each time. For quick renders, don't use VBOs
