### ISSUE TITLE
Jitpack build failed, please rebuild

### ISSUE THREAD

**Issue by kevinthegreat1** [0x3C50/Renderer#20]
The jitpack build failed, causing the newest version to be unusable, which is required for 1.19.4. You can log in on jitpack, select `builds` and click the x on the right of newest build (`0b4ebfcf45`) to rebuild.

**Comment by 0x3C50** [comment]
![grafik](https://user-images.githubusercontent.com/99053360/225128488-e554768a-66d5-4823-8207-a058adce3929.png)
huh

**Comment by 0x3C50** [comment]
found the issue, loom 1.1-SNAPSHOT fails to build it. i'll push a fix

**Comment by 0x3C50** [comment]
push is fixed, i'll wait a bit before letting jitpack rebuild for it to update
