### ISSUE TITLE
FEATURE REQUEST: glowing effect rendering

### ISSUE THREAD

**Issue by danik4985** [0x3C50/Renderer#22]
Hello, I was just thinking if you implemented a way to render a glowing-like effect but with custom color and position and size and possibly custom line width. I'm bad at rendering so idk how hard it would be to make, so sorry if its too hard, anyways thanks.

**Comment by 0x3C50** [comment]
what do you mean with "custom line width"?

**Comment by danik4985** [comment]
like to be able to make the glow line fatter or thiner

![](https://media.discordapp.net/attachments/733703994018496564/1101887114506944592/sketch.png)

no idea if its even possible tho, im bad at rendering

**Comment by 0x3C50** [comment]
oh THAT kind of glow
yeah that'll be possible, i can get around to doing that soon

**Comment by danik4985** [comment]
thank you

**Comment by danik4985** [comment]
Thank you, although it seems I am unable to draw multiple of these at the same time (only the first `useAndDraw` I call gets drawn). Any idea how can I fix that? Or is that intended?

**Comment by 0x3C50** [comment]
> Thank you, although it seems I am unable to draw multiple of these at the same time (only the first `useAndDraw` I call gets drawn). Any idea how can I fix that? Or is that intended?

that is not intended, give me a second

**Comment by 0x3C50** [comment]
fixed, ended up being an issue with mojang code once again
