### ISSUE TITLE
Issue with two rounded rectangles

### ISSUE THREAD

**Issue by Otter-Lover** [0x3C50/Renderer#33]
# Bug Description

I'm trying to create a some ui elements and I'm creating two boxes, though when I create the second box when I try to make it rounded it seems to go.. well all over the place (as seen in the screenshot below), It works perfectly fine if I don't try to round it (though ofc it won't be rounded).

I'm running 1.20.1 if that is needed info

# Code
```java
public void render(DrawContext context, int mousex, int mousey, float delta) {
        MatrixStack fs = context.getMatrices();
        fs.push();

        Renderer2d.renderRoundedQuad(fs, Color.BLACK, 15,15, 100, 30, 3, 5);
        Renderer2d.renderRoundedQuad(fs, Color.BLACK, 80,80, 150, 60, 3,5);

        font.drawString(fs, "Fun Text", 15, 15, 1f, 1f, 1f, 1f);
        font.drawString(fs, "Fun Text v3", 80, 60, 1f, 1f, 1f, 1f);
        
        fs.pop();
    }
```

# Expected Behavior

The second box goes all over the place when rendering

# Screenshots
![image](https://github.com/0x3C50/Renderer/assets/89653989/cca0b74c-2c8c-4658-9004-d6524b072a1b)

# Desktop
 - OS: Windows 11
- GPU: AMD Radeon RX 6600

**Comment by 0x3C50** [comment]
your y end coordinate on the second box is lower than your y start. the start coordinates always need to be lower than the end coordinates
