### ISSUE TITLE
Rendering .obj

### ISSUE THREAD

**Issue by Scrait** [0x3C50/Renderer#38]
it just doesn't render .obj

**Comment by 0x3C50** [comment]
i cant read your mind. which obj file are you trying to render? how are you trying to render it? where in the rendering pipeline is your code running at?

**Comment by Scrait** [comment]
https://www.artec3d.com/3d-models/axle-shaft 
I'm trying to render this obj file, here is the code

@Subscribe
    public void onWorldRender(WorldRenderEvent event) throws IOException {
        if (objFile == null) {
            String directoryPath = "C:/Users/scrai/Desktop/drainwalk 3.0/run/data/";
            Path directory = Paths.get(directoryPath);
            objFile = new ObjFile("Screw.obj", ObjFile.ResourceProvider.ofPath(directory));
        }
        objFile.draw(event.getContext().matrixStack(), new Matrix4f(), new Vec3d(0, 400, 0));
    }

**Comment by Scrait** [comment]
> i cant read your mind. which obj file are you trying to render? how are you trying to render it? where in the rendering pipeline is your code running at?

https://www.artec3d.com/3d-models/axle-shaft
I'm trying to render this obj file, here is the code

@subscribe
public void onWorldRender(WorldRenderEvent event) throws IOException {
if (objFile == null) {
String directoryPath = "C:/Users/scrai/Desktop/drainwalk 3.0/run/data/";
Path directory = Paths.get(directoryPath);
objFile = new ObjFile("Screw.obj", ObjFile.ResourceProvider.ofPath(directory));
}
objFile.draw(event.getContext().matrixStack(), new Matrix4f(), new Vec3d(0, 400, 0));
}

**Comment by 0x3C50** [comment]
and you're 100% sure the code runs?

**Comment by Scrait** [comment]
> and you're 100% sure the code runs?

yeah

**Comment by 0x3C50** [comment]
can you send the screw.obj file here

**Comment by 0x3C50** [comment]
closing since no details were given. if needed, reopen
