### ISSUE TITLE
Unrendering

### ISSUE THREAD

**Issue by ada-mmmm** [0x3C50/Renderer#4]
So sorry to bother you again, but how do I unrender something?

**Comment by 0x3C50** [comment]
please elaborate

**Comment by ada-mmmm** [comment]
I'm making a toggle to turn the GUI on and off but I'm not sure how to turn it off.

**Comment by 0x3C50** [comment]
make a flag and just dont render it when the flag is set

**Comment by ada-mmmm** [comment]
hi so i'm trying something like this but its not opening. 

public class EventHandler {
    Color c = new Color(96, 157, 114, 52);
    public boolean isOpen = false;

   @EventListener(shift= Shift.POST, type = EventType.HUD_RENDER)
    void preHudRender(RenderEvent re) {
       MSAAFramebuffer.use(MSAAFramebuffer.MAX_SAMPLES, () -> {
           ClipStack.globalInstance.addWindow(re.getStack(),new Rectangle(0,0,115,80));
           ClipStack.globalInstance.popWindow();

       });
       ClientTickEvents.END_CLIENT_TICK.register(client -> {
           while (keyBinding.wasPressed()) {

               assert client.player != null;
               if(!isOpen) {
                   client.player.sendMessage(new LiteralText("[Debug]: Opened GUI"),false);
                   Renderer2d.renderRoundedQuad(re.getStack(), c,0,0,115,115,3,10);
                   
                   isOpen = true;
               } else {
                   client.player.sendMessage(new LiteralText("[Debug]: Closed GUI"),false);
                   isOpen = false;

               }


           }
       });

    }


}

**Comment by 0x3C50** [comment]
Can you format your entire code in that code block format? its a bit hard to read right now

**Comment by ada-mmmm** [comment]
`public class EventHandler {
    Color c = new Color(96, 157, 114, 52);
    public boolean isOpen = false;

   @EventListener(shift= Shift.POST, type = EventType.HUD_RENDER)
    void preHudRender(RenderEvent re) {
       MSAAFramebuffer.use(MSAAFramebuffer.MAX_SAMPLES, () -> {
           ClipStack.globalInstance.addWindow(re.getStack(),new Rectangle(0,0,115,80));
           ClipStack.globalInstance.popWindow();

       });
       ClientTickEvents.END_CLIENT_TICK.register(client -> {
           while (keyBinding.wasPressed()) {

               assert client.player != null;
               if(!isOpen) {
                   client.player.sendMessage(new LiteralText("[Debug]: Opened GUI"),false);
                   Renderer2d.renderRoundedQuad(re.getStack(), c,0,0,115,115,3,10);

                   isOpen = true;
               } else {
                   client.player.sendMessage(new LiteralText("[Debug]: Closed GUI"),false);
                   isOpen = false;

               }


           }
       });

    }


}`

**Comment by ada-mmmm** [comment]
```
public class EventHandler {
    Color c = new Color(96, 157, 114, 52);
    public boolean isOpen = false;

   @EventListener(shift= Shift.POST, type = EventType.HUD_RENDER)
    void preHudRender(RenderEvent re) {
       MSAAFramebuffer.use(MSAAFramebuffer.MAX_SAMPLES, () -> {
           ClipStack.globalInstance.addWindow(re.getStack(),new Rectangle(0,0,115,80));
           ClipStack.globalInstance.popWindow();

       });
       ClientTickEvents.END_CLIENT_TICK.register(client -> {
           while (keyBinding.wasPressed()) {

               assert client.player != null;
               if(!isOpen) {
                   client.player.sendMessage(new LiteralText("[Debug]: Opened GUI"),false);
                   Renderer2d.renderRoundedQuad(re.getStack(), c,0,0,115,115,3,10);

                   isOpen = true;
               } else {
                   client.player.sendMessage(new LiteralText("[Debug]: Closed GUI"),false);
                   isOpen = false;

               }


           }
       });

    }


}
```

**Comment by ada-mmmm** [comment]
sorry for taking a while i was sick :/ also happy easter :)

**Comment by 0x3C50** [comment]
you're using while, which blocks the thread. use if

**Comment by 0x3C50** [comment]
also, you're not rendering consistently, you're rendering once.

also also, you're registering a new event each time the hud is rendered. don't do that. register both events once, and listen for the flag on the render event handler, and modify the flag on the tick event handler
