### ISSUE TITLE
Bad class file when building

### ISSUE THREAD

**Issue by GoldenShad0w** [0x3C50/Renderer#42]
# Bug Description
Im trying to use this library for my mod but if i try to compile, it fails and says it can't find any Events classes

# Code
```java
import net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents;
                                                        ^
  bad class file: /.../.gradle/loom-cache/remapped_mods/net_fabricmc_yarn_1_20_2_1_20_2_build_4_v2/net/fabricmc/fabric-api/fabric-lifecycle-events-v1/2.3.4+c5fc38b30d/fabric-lifecycle-events-v1-2.3.4+c5fc38b30d.jar(/net/fabricmc/fabric/api/client/event/lifecycle/v1/ClientLifecycleEvents.class)
    class file has wrong version 65.0, should be 61.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

# Desktop
 - OS: MacOS
- GPU: M2

**Comment by 0x3C50** [comment]
irrelevant to the library. your java version is too old

**Comment by GoldenShad0w** [comment]
so i would need to use java 21 but I can't because im on 1.20.2?

**Comment by 0x3C50** [comment]
i dont know what you've been trying, but it has nothing to do with the library

**Comment by GoldenShad0w** [comment]
Well im trying to make this library work with my 1.20.2 mod but as you said, i need to use java 21 for that to work. However, if I switch to java 21, then the fabric launcher tells me to upgrade to 1.20.5+
