### ISSUE TITLE
1.21 Update

### ISSUE THREAD

**Issue by bruh1273** [0x3C50/Renderer#43]
Just a few days ago (at the time of making this issue) Minecraft has updated to 1.21. 
My mod, and many other mods people develop relies on this library to fundamentally function. 
With that said, a 1.21 update will unlock the ability for all of us to update our mods to the latest Minecraft version.

**Comment by 0x3C50** [comment]
waited on satin to update, seems like they updated. working on it now

**Comment by 0x3C50** [comment]
updated
