### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by JOEVERING** [0x3C50/Renderer#46]
Hi, i rly like this library so far and i have a suggestion that i think not many mods/clients have implemented:
Basically it would be cool to be able to blur parts of the screen (like the new 1.21 pause menu background) but in select rects/areas.
And maybe even be able to control how much blur there is or the blur color(?). i think that would be awesom and im too dumb to do it myself lol

**Comment by 0x3C50** [comment]
forgot to close this, it is done
