### ISSUE TITLE
Could not find com.github.0x3C50:Renderer:master-SNAPSHOT

### ISSUE THREAD

**Issue by liroxdeyamon** [0x3C50/Renderer#54]
# Bug Description
It can't build cuz it can't find library

# Code
Haven't wrote any yet, just edited gradle as library said:
```
repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}
dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    include modImplementation("com.github.0x3C50:Renderer:master-SNAPSHOT")
}
```

# Expected Behavior
For it to build lol

# Screenshots
No screenshots

# Desktop
 - OS: Windows 11
- GPU: Built-in Intel core i3

# Additional Context
[log.txt](https://github.com/user-attachments/files/18136141/log.txt)
if need any more - just ask

**Comment by 0x3C50** [comment]
https://github.com/0x3C50/Renderer/blob/master/README.md#installing jitpack is long out of date
