### ISSUE TITLE
Game Crashing on Launch

### ISSUE THREAD

**Issue by Tobejizzle** [0x3C50/Renderer#8]
I recently updated to 1.19 and upgraded my gradle settings. I got the game running however when I implemented the renderer it gives me this : 

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Renderer' (renderer) 1.0 with any version that is compatible with:
		 - minecraft 1.19
Unmet dependency listing:
	 - Mod 'Renderer' (renderer) 1.0 requires version 1.18.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

I did not change the "include modImplementation("com.github.0x3C50:Renderer:master-SNAPSHOT")" because it says it will automatically update.

**Comment by 0x3C50** [comment]
i forgot to change the version lmfao 1s

**Comment by 0x3C50** [comment]
alr its pushed, give it a few mins then try to reload gradle

**Comment by Tobejizzle** [comment]
ite thanks bro

**Comment by Tobejizzle** [comment]
i hate to bother u again but its still giving me the same error. 

is there something i need to change on my end other than reloading my gradle?

**Comment by Tobejizzle** [comment]
works :) thanks
